In [1]:
import pandas as pd
print(pd.__version__)
df = pd.DataFrame({"a":[1,2,3]})
print(df)



2.3.3
   a
0  1
1  2
2  3


In [2]:
!pip install tensorflow
!pip install keras
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9419, 9552, 6187, 5626],
 [9419, 9552, 6187, 9714],
 [9419, 8331, 6187, 4946],
 [1546, 2717, 464, 1735, 2698],
 [1546, 2717, 464, 1735, 6837],
 [5571, 9419, 4595, 6187, 7969],
 [9290, 7143, 4328, 1735]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9419 9552 6187 5626]
 [   0    0    0    0 9419 9552 6187 9714]
 [   0    0    0    0 9419 8331 6187 4946]
 [   0    0    0 1546 2717  464 1735 2698]
 [   0    0    0 1546 2717  464 1735 6837]
 [   0    0    0 5571 9419 4595 6187 7969]
 [   0    0    0    0 9290 7143 4328 1735]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\User\Desktop\CODE\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 345ms/step


array([[[-1.3011515e-02, -4.1410841e-02, -1.3808537e-02,  2.9418580e-03,
          1.3707232e-02,  1.5546311e-02,  4.9170818e-02, -3.4966320e-04,
          8.9527294e-04,  4.8423778e-02],
        [-1.3011515e-02, -4.1410841e-02, -1.3808537e-02,  2.9418580e-03,
          1.3707232e-02,  1.5546311e-02,  4.9170818e-02, -3.4966320e-04,
          8.9527294e-04,  4.8423778e-02],
        [-1.3011515e-02, -4.1410841e-02, -1.3808537e-02,  2.9418580e-03,
          1.3707232e-02,  1.5546311e-02,  4.9170818e-02, -3.4966320e-04,
          8.9527294e-04,  4.8423778e-02],
        [-1.3011515e-02, -4.1410841e-02, -1.3808537e-02,  2.9418580e-03,
          1.3707232e-02,  1.5546311e-02,  4.9170818e-02, -3.4966320e-04,
          8.9527294e-04,  4.8423778e-02],
        [ 1.9868899e-02,  2.0123508e-02,  4.5571256e-02, -8.6923726e-03,
          3.7308719e-02,  1.1022020e-02, -1.5135132e-02,  4.1435067e-02,
         -8.0499537e-03,  4.0060170e-03],
        [ 3.7827119e-03, -3.4410845e-02,  1.9640055e-02, -4.

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 9419, 9552, 6187, 5626], dtype=int32)

In [16]:
model.predict(np.array([embedded_docs[0]]))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step


array([[[-1.3011515e-02, -4.1410841e-02, -1.3808537e-02,  2.9418580e-03,
          1.3707232e-02,  1.5546311e-02,  4.9170818e-02, -3.4966320e-04,
          8.9527294e-04,  4.8423778e-02],
        [-1.3011515e-02, -4.1410841e-02, -1.3808537e-02,  2.9418580e-03,
          1.3707232e-02,  1.5546311e-02,  4.9170818e-02, -3.4966320e-04,
          8.9527294e-04,  4.8423778e-02],
        [-1.3011515e-02, -4.1410841e-02, -1.3808537e-02,  2.9418580e-03,
          1.3707232e-02,  1.5546311e-02,  4.9170818e-02, -3.4966320e-04,
          8.9527294e-04,  4.8423778e-02],
        [-1.3011515e-02, -4.1410841e-02, -1.3808537e-02,  2.9418580e-03,
          1.3707232e-02,  1.5546311e-02,  4.9170818e-02, -3.4966320e-04,
          8.9527294e-04,  4.8423778e-02],
        [ 1.9868899e-02,  2.0123508e-02,  4.5571256e-02, -8.6923726e-03,
          3.7308719e-02,  1.1022020e-02, -1.5135132e-02,  4.1435067e-02,
         -8.0499537e-03,  4.0060170e-03],
        [ 3.7827119e-03, -3.4410845e-02,  1.9640055e-02, -4.